### ISSUE TITLE
Having a StackOverflowException error while extracting Twilight Princess

### ISSUE THREAD

**Issue by imsl0wer** [Venomalia/DolphinTextureExtraction-tool#19]
it dumps like half the textures and then crashes 
LOG: [10] Extract: files\res\Object\Hzelda\bmdr\ef_triangleat\tex1_32x32_e6cc95d5e33a7e6f_1.png
• mips:0 WrapS:REPEAT WrapT:REPEAT LODBias:0 MinLOD:0 MaxLOD:0
Warning: Material zelda_doubleside_m_v, TexMatrix2Block index out of range: 0
Warning: Material zelda_doubleside_m_v, TexMatrix2Block index out of range: 0
[08] Unknown: files\res\Object\Hoz\evt\event_list.dat ~16.73KB
• Bytes32:[00-00-00-40-00-00-00-08-00-00-05-C0-00-00-00-1D-00-00-0E-D0-00-00-00-4A-00-00-25-F0-00-00-00-68]

**Comment by Venomalia** [comment]
I will probably deal with it in the next week.

**Comment by Venomalia** [comment]
use this https://github.com/Venomalia/DolphinTextureExtraction-tool/releases
