### ISSUE TITLE
killer7 pc port textures issue 

### ISSUE THREAD

**Issue by sal-4** [Venomalia/DolphinTextureExtraction-tool#40]
Hi, thanks for the great tool! It works perfect on the GC version of killer7. 
If its not too much trouble, would it be possible to make it also work with the killer7 PC port that came out 2018?

I attached two files, one of the Gamecube and one from the PC port.
Maybe I am just not using it right.
[GC_map.pak.zip](https://github.com/Venomalia/DolphinTextureExtraction-tool/files/11645211/GC_map.pak.zip)
[PC_map.pak.zip](https://github.com/Venomalia/DolphinTextureExtraction-tool/files/11645213/PC_map.pak.zip)
As far as I unterstand, there is a header added on the pc version. It would make extracting images a much smoother experience, if it worked.

Thank you kindly,
sal4

**Comment by Venomalia** [comment]
ou can unpack the RSL archive from the PC version with the tool into the individual files but the texture format is completely different, of course it would be possible but it would be a lot of effort.
maybe you can find a tool which can read the unpacked files.

**Comment by sal-4** [comment]
> ou can unpack the RSL archive from the PC version with the tool into the individual files but the texture format is completely different, of course it would be possible but it would be a lot of effort. maybe you can find a tool which can read the unpacked files.

Thanks! I had no idea it would be so much trouble, but it makes sense. It seems like the images are *.DDS files with a K7TX header.

Thanks for the fast reply, I have found a workaround with just editing out the first header part and I can open it with paint.net.
Cheers,
sal4
