### ISSUE TITLE
Support for Eternal Darkness: Sanity's Requiem

### ISSUE THREAD

**Issue by fotisandstuff** [Venomalia/DolphinTextureExtraction-tool#50]
Hello! I've been using DTE with Eternal Darkness' files (extracted from the RVZ image using Dolphin). It could only extract a few .png files (and a lot of .tpl files, when the "extract raw files" optiion is selected). I managed to extract a lot more (but not all of them) using this method:

1) I ran the tool [Decompress Eternal Darkness](https://github.com/jombo23/N64-Tools/tree/master/DecompressEternalDarkness).
2) I removed the ".decompressed" part from the filenames of the resulting files.
3) I ran DTE on them.

I combined the results from both the original and decompressed files (by removing the duplicates), using both the default settings of DTE and the modified settings (I set the extraction of Unknown and Raw files to True). Now I have 994 PNG textures, 1826 .tpl files, and a bunch of other unrecognized file formats (.aig, .bin, .gct, .nut, .txd). There are still some textures that I can't find in the PNG's, such as the one of the protagonist, Alexandra Roivas. Could they be locked inside the .tpl files? What else can I do to fully extract all textures (other than playing the game to dump the textures, as that is highly annoying due to Dolphin constantly dumping the frames of animated textures over and over again)?

**Comment by Venomalia** [comment]
tpl files are a nintendo image format you can extract them with the DTE tool and get the .png files.

**Comment by fotisandstuff** [comment]
Thank you!
