### ISSUE TITLE
Exception While Dumping Wii Games: Specified key is not a valid size for this algorithm.

### ISSUE THREAD

**Issue by zicklag** [Venomalia/DolphinTextureExtraction-tool#52]
Hey there! First off, big thanks for this tool! It's been working great for my gamecube games.

I haven't been able to successfully dump any of my Wii games yet, though. I initially thought that was because the Wii ISOs I had were in two parts, due to the dumper I was using, but after producing a single-part ISO for a different game, I have the same issue:

```
[01] Exception: R92E01.iso Specified key is not a valid size for this algorithm.
```

Is there anything I can do to look into the root cause of this error?

**Comment by Venomalia** [comment]
It seems that I have broken the Wii decryption.

Unpack the game with dolphin as a folder and then use the tool.

**Comment by zicklag** [comment]
Thanks that worked! Should I leave this issue open for now?
