### ISSUE TITLE
Regression Since v1.5.4.531 When Dumping Mario Party 6 ( US )

### ISSUE THREAD

**Issue by zicklag** [Venomalia/DolphinTextureExtraction-tool#53]
Using the latest release `v1.7.13.1014` I am able to extract less than 2000 textures from the US version of Mario Party 6, but using an older version `v1.5.4.531` I am able to get more than 8000 textures.

**Comment by Venomalia** [comment]
this is a small error with the HSF files that they are not recognized, I will fix that.

thanks for the info.
